name: human-action-classification
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - attrs==25.4.0
      - black==25.9.0
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - distlib==0.4.0
      - exceptiongroup==1.3.0
      - fastapi==0.119.1
      - ffmpy==0.6.4
      - filelock==3.20.0
      - flake8==7.3.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - iniconfig==2.3.0
      - isort==7.0.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lark==1.3.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - protobuf==4.25.8
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytokens==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - starlette==0.48.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - virtualenv==20.35.3
      - wandb==0.22.2
      - websockets==15.0.1
      - werkzeug==3.1.3
